### ISSUE TITLE
Multiple compilation processes run without parallelExecution in Global := false

### ISSUE THREAD

**Issue by xerial** [typesafehub/sbt-multi-jvm#15]
In sbt-0.13 (and sbt-multi-jvm 0.3.8), we should set parallelExecution flag to false in the Global context:

    parallelExcecution in Global := false

Without this setting, it looks like multiple compilation tasks run simultaneously and it causes an exeception described as below:

```
java.lang.RuntimeException: Could not create directory target/classes.bak
	at scala.sys.package$.error(package.scala:27)
	at sbt.IO$.createDirectory(IO.scala:155)
	at sbt.inc.ClassfileManager$$anonfun$transactional$1$$anon$2.<init>(ClassfileManager.scala:37)
	at sbt.inc.ClassfileManager$$anonfun$transactional$1.apply(ClassfileManager.scala:33)
	at sbt.inc.ClassfileManager$$anonfun$transactional$1.apply(ClassfileManager.scala:33)
```

**Comment by ktoso** [comment]
This plugin has moved homes and now lives in: https://github.com/sbt/sbt-multi-jvm (ported issues)
