### ISSUE TITLE
support ide testing

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [typesafehub/sbt-multi-jvm#20]
need some equivalent of
```
@org.junit.runner.RunWith(classOf[org.scalatest.junit.JUnitRunner])
```
to allow running multi-jvm tests in eclipse and idea

**Comment by patriknw** [comment]
that would be challenging (I think), they are run by a special sbt plugin

**Comment by Andrei-Pozolotin** [comment]
it "almost works" in eclipse:
```
Eclipse -> Run As -> ScalaTest - File
```

```
Exception in thread "main" java.lang.NoClassDefFoundError: scala/Function1
	at scala.tools.eclipse.scalatest.launching.ScalaTestLauncher.main(ScalaTestLauncher.scala)
Caused by: java.lang.ClassNotFoundException: scala.Function1
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
```
I guess, different classloader contract, again: [ScalaTestLauncher](https://github.com/scalatest/scalatest-eclipse-plugin/blob/master/org.scala-ide.sdt.scalatest/src/scala/tools/eclipse/scalatest/launching/ScalaTestLauncher.scala)

**Comment by ktoso** [comment]
This plugin has moved homes and now lives in: https://github.com/sbt/sbt-multi-jvm (ported issues)
