### ISSUE TITLE
Please upgrade dependency on sbt assembly plugin

### ISSUE THREAD

**Issue by agemooij** [typesafehub/sbt-multi-jvm#21]
Our project is currently unable to upgrade to the latest version of the sbt-assembly plugin (0.12.0) because this plugin depends on an incompatibly old version (0.8.5). This will lead to the following exception when starting SBT:

    java.lang.NoClassDefFoundError: sbtassembly/Plugin$

It would be great if this conflicting dependency would be removed or worked around so this plugin will not block projects from using the latest version of the sbt-assembly plugin.

sbt version: 0.13.7
java version: 1.8.0_25
Complete stack trace:

    java.lang.NoClassDefFoundError: sbtassembly/Plugin$
      at com.typesafe.sbt.SbtMultiJvm$.internalMultiJvmSettings(SbtMultiJvm.scala:78)
      at com.typesafe.sbt.SbtMultiJvm$.multiJvmSettings$lzycompute(SbtMultiJvm.scala:76)
      at com.typesafe.sbt.SbtMultiJvm$.multiJvmSettings(SbtMultiJvm.scala:76)
      at Cluster$.clusterSettings$lzycompute(Cluster.scala:7)
      at Cluster$.clusterSettings(Cluster.scala:7)
      at Build$.rebbShopper$lzycompute(Build.scala:212)
      at Build$.rebbShopper(Build.scala:203)
      at Build$.rebbWebsite$lzycompute(Build.scala:287)
      at Build$.rebbWebsite(Build.scala:281)
      at Build$.rebbMultiJvmTest$lzycompute(Build.scala:257)
      at Build$.rebbMultiJvmTest(Build.scala:253)
      at Build$.root$lzycompute(Build.scala:42)
      at Build$.root(Build.scala:31)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:483)
      at sbt.ReflectUtilities$$anonfun$allValsC$1$$anonfun$apply$2.apply(ReflectUtilities.scala:45)
      at sbt.ReflectUtilities$$anonfun$allValsC$1$$anonfun$apply$2.apply(ReflectUtilities.scala:44)
      at scala.Option$WithFilter.foreach(Option.scala:208)
      at sbt.ReflectUtilities$$anonfun$allValsC$1.apply(ReflectUtilities.scala:44)
      at sbt.ReflectUtilities$$anonfun$allValsC$1.apply(ReflectUtilities.scala:42)
      at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
      at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
      at sbt.ReflectUtilities$.allValsC(ReflectUtilities.scala:42)
      at sbt.ReflectUtilities$.allVals(ReflectUtilities.scala:61)
      at sbt.Build$class.projects(Build.scala:13)
      at Build$.projects(Build.scala:10)
      at sbt.Build$class.projectDefinitions(Build.scala:12)
      at Build$.projectDefinitions(Build.scala:10)
      at sbt.Load$.sbt$Load$$projectsFromBuild(Load.scala:496)
      at sbt.Load$$anonfun$27.apply(Load.scala:436)
      at sbt.Load$$anonfun$27.apply(Load.scala:436)
      at scala.collection.immutable.Stream.flatMap(Stream.scala:442)
      at sbt.Load$.loadUnit(Load.scala:436)
      at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
      at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
      at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
      at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
      at sbt.BuildLoader.apply(BuildLoader.scala:140)
      at sbt.Load$.loadAll(Load.scala:334)
      at sbt.Load$.loadURI(Load.scala:289)
      at sbt.Load$.load(Load.scala:285)
      at sbt.Load$.load(Load.scala:276)
      at sbt.Load$.apply(Load.scala:130)
      at sbt.Load$.defaultLoad(Load.scala:36)
      at sbt.BuiltinCommands$.doLoadProject(Main.scala:481)
      at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
      at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
      at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
      at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
      at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
      at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
      at sbt.Command$.process(Command.scala:92)
      at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
      at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
      at sbt.State$$anon$1.process(State.scala:184)
      at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
      at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
      at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
      at sbt.MainLoop$.next(MainLoop.scala:98)
      at sbt.MainLoop$.run(MainLoop.scala:91)
      at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
      at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
      at sbt.Using.apply(Using.scala:24)
      at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
      at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
      at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
      at sbt.MainLoop$.runLogged(MainLoop.scala:24)
      at sbt.StandardMain$.runManaged(Main.scala:53)
      at sbt.xMain.run(Main.scala:28)
      at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
      at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
      at xsbt.boot.Launch$.run(Launch.scala:109)
      at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
      at xsbt.boot.Launch$.launch(Launch.scala:117)
      at xsbt.boot.Launch$.apply(Launch.scala:18)
      at xsbt.boot.Boot$.runImpl(Boot.scala:41)
      at xsbt.boot.Boot$.main(Boot.scala:17)
      at xsbt.boot.Boot.main(Boot.scala)
    Caused by: java.lang.ClassNotFoundException: sbtassembly.Plugin$
      at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
      at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
      at java.security.AccessController.doPrivileged(Native Method)
      at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
      at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
      at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
      at com.typesafe.sbt.SbtMultiJvm$.internalMultiJvmSettings(SbtMultiJvm.scala:78)
      at com.typesafe.sbt.SbtMultiJvm$.multiJvmSettings$lzycompute(SbtMultiJvm.scala:76)
      at com.typesafe.sbt.SbtMultiJvm$.multiJvmSettings(SbtMultiJvm.scala:76)
      at Cluster$.clusterSettings$lzycompute(Cluster.scala:7)
      at Cluster$.clusterSettings(Cluster.scala:7)
      at Build$.rebbShopper$lzycompute(Build.scala:212)
      at Build$.rebbShopper(Build.scala:203)
      at Build$.rebbWebsite$lzycompute(Build.scala:287)
      at Build$.rebbWebsite(Build.scala:281)
      at Build$.rebbMultiJvmTest$lzycompute(Build.scala:257)
      at Build$.rebbMultiJvmTest(Build.scala:253)
      at Build$.root$lzycompute(Build.scala:42)
      at Build$.root(Build.scala:31)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:483)
      at sbt.ReflectUtilities$$anonfun$allValsC$1$$anonfun$apply$2.apply(ReflectUtilities.scala:45)
      at sbt.ReflectUtilities$$anonfun$allValsC$1$$anonfun$apply$2.apply(ReflectUtilities.scala:44)
      at scala.Option$WithFilter.foreach(Option.scala:208)
      at sbt.ReflectUtilities$$anonfun$allValsC$1.apply(ReflectUtilities.scala:44)
      at sbt.ReflectUtilities$$anonfun$allValsC$1.apply(ReflectUtilities.scala:42)
      at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
      at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
      at sbt.ReflectUtilities$.allValsC(ReflectUtilities.scala:42)
      at sbt.ReflectUtilities$.allVals(ReflectUtilities.scala:61)
      at sbt.Build$class.projects(Build.scala:13)
      at Build$.projects(Build.scala:10)
      at sbt.Build$class.projectDefinitions(Build.scala:12)
      at Build$.projectDefinitions(Build.scala:10)
      at sbt.Load$.sbt$Load$$projectsFromBuild(Load.scala:496)
      at sbt.Load$$anonfun$27.apply(Load.scala:436)
      at sbt.Load$$anonfun$27.apply(Load.scala:436)
      at scala.collection.immutable.Stream.flatMap(Stream.scala:442)
      at sbt.Load$.loadUnit(Load.scala:436)
      at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
      at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
      at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
      at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
      at sbt.BuildLoader.apply(BuildLoader.scala:140)
      at sbt.Load$.loadAll(Load.scala:334)
      at sbt.Load$.loadURI(Load.scala:289)
      at sbt.Load$.load(Load.scala:285)
      at sbt.Load$.load(Load.scala:276)
      at sbt.Load$.apply(Load.scala:130)
      at sbt.Load$.defaultLoad(Load.scala:36)
      at sbt.BuiltinCommands$.doLoadProject(Main.scala:481)
      at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
      at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
      at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
      at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
      at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
      at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
      at sbt.Command$.process(Command.scala:92)
      at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
      at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
      at sbt.State$$anon$1.process(State.scala:184)
      at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
      at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
      at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
      at sbt.MainLoop$.next(MainLoop.scala:98)
      at sbt.MainLoop$.run(MainLoop.scala:91)
      at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
      at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
      at sbt.Using.apply(Using.scala:24)
      at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
      at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
      at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
      at sbt.MainLoop$.runLogged(MainLoop.scala:24)
      at sbt.StandardMain$.runManaged(Main.scala:53)
      at sbt.xMain.run(Main.scala:28)
      at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
      at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
      at xsbt.boot.Launch$.run(Launch.scala:109)
      at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
      at xsbt.boot.Launch$.launch(Launch.scala:117)
      at xsbt.boot.Launch$.apply(Launch.scala:18)
      at xsbt.boot.Boot$.runImpl(Boot.scala:41)
      at xsbt.boot.Boot$.main(Boot.scala:17)
      at xsbt.boot.Boot.main(Boot.scala)

**Comment by patriknw** [comment]
Sounds good. Pull request?

**Comment by bantonsson** [comment]
So there is a PR #19 that updates the plugin and it's dependencies. I haven't had the time to look at it or test it against the akka build, but it would at least be a good start.

**Comment by agemooij** [comment]
#19 indeed looks like it would solve this. +1 for merging that and then publishing a new release.

**Comment by ktoso** [comment]
This plugin has moved homes and now lives in: https://github.com/sbt/sbt-multi-jvm (ported issues)
